#!/bin/bash -e

SCRIPT_DIR="`dirname $0`"
PRJ="$SCRIPT_DIR/../.."

mockgen -source=$PRJ/utils/fileutils/fileutils.go >$PRJ/utils/fileutils/mock_fileutils/mock_fileutils.go
mockgen -source=$PRJ/utils/syscall/syscall.go >$PRJ/utils/syscall/mock_syscall/mock_syscall.go
